// Regenerates the inline SVG sprite in src/popup.html from a Lucide checkout (ISC licence).
//   npm pack lucide-static && tar xzf lucide-static-*.tgz
//   node scripts/build-icons.mjs package/icons
// Add a name to ICONS, re-run, commit popup.html. The sprite lives inline so the icons cost no extra request.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

export const ICONS = [
  'archive', 'arrow-down-left', 'arrow-left', 'arrow-up-right', 'bell-off', 'bookmark', 'bot', 'brain', 'calendar', 'chart-column',
  'check', 'chevron-down', 'chevron-right', 'circle-alert', 'circle-x', 'clipboard', 'clipboard-list', 'clock', 'cloud', 'copy',
  'download', 'ellipsis', 'eraser', 'external-link', 'file-text', 'folders', 'globe', 'headphones', 'info', 'laptop',
  'layers', 'lightbulb', 'link', 'lock', 'loader', 'message-square', 'network', 'newspaper', 'palette', 'paperclip', 'pause', 'pencil', 'pin',
  'play', 'plus', 'refresh-cw', 'ruler', 'save', 'search', 'send', 'server', 'settings', 'share-2', 'sliders-horizontal',
  'smartphone', 'smile', 'sparkles', 'square-check-big', 'star', 'tag', 'trash-2', 'undo-2', 'upload', 'user',
  'volume-2', 'volume-x', 'x',
];

const src = process.argv[2];
if (!src) { console.error('usage: node scripts/build-icons.mjs <lucide-static/icons dir>'); process.exit(1); }
const html = join(dirname(fileURLToPath(import.meta.url)), '..', 'src', 'popup.html');

const symbols = ICONS.map((n) => {
  const svg = readFileSync(join(src, n + '.svg'), 'utf8');
  const inner = svg.replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>[\s\S]*$/, '').replace(/\s*\n\s*/g, '').trim();
  return `<symbol id="i-${n}" viewBox="0 0 24 24">${inner}</symbol>`;
}).join('\n');
const block = `<!-- icons:start (generated by scripts/build-icons.mjs from Lucide, ISC) -->
<svg xmlns="http://www.w3.org/2000/svg" width="0" height="0" style="position:absolute" aria-hidden="true" focusable="false">
${symbols}
</svg>
<!-- icons:end -->`;
const cur = readFileSync(html, 'utf8');
const next = /<!-- icons:start[\s\S]*?<!-- icons:end -->/.test(cur)
  ? cur.replace(/<!-- icons:start[\s\S]*?<!-- icons:end -->/, () => block)
  : cur.replace(/<body[^>]*>/, (m) => m + '\n    ' + block);
writeFileSync(html, next);
console.log(`sprite: ${ICONS.length} icons`);
