// Long texts: scroll-to-top pill + contents ring (shown only when long, scrolling up; contents needs >= 3 headings).
import { setup, imp } from './harness.mjs'; import assert from 'assert';
const { w } = setup({}); const d = w.document; globalThis.document = d; globalThis.window = w;
const rt = await imp('modules/readingTools.js');
d.body.dataset.screen = 'history';
const scroller = d.getElementById('historyScreen');
const detail = d.getElementById('articleDetail'); detail.style.display = 'block';
const content = d.getElementById('articleDetailContent');
content.innerHTML = '<div class="article-detail-card"><h3>Title</h3><div id="qaMount"><h2>Q&A</h2></div><details><summary>Original</summary><div><h2>Intro</h2><p>x</p><h2>Method</h2><h3>Data</h3><h2>Results</h2></div></details></div>';
const heads = rt.collectHeadings(content);
assert.deepEqual(heads.map(h => h.text), ['Intro', 'Method', 'Data', 'Results'], 'title and Q&A skipped');
const set = (o) => { for (const [k, v] of Object.entries(o)) Object.defineProperty(scroller, k, { value: v, configurable: true, writable: true }); };
set({ clientHeight: 600, scrollHeight: 6000, scrollTop: 0 });
const t = rt.mountReadingTools({ scroller, content });
assert(t && t.hasToc && d.querySelector('.rt-ring') && d.querySelector('.rt-pill'));
assert(!t.root.classList.contains('is-on'), 'hidden at the top');
set({ scrollTop: 2000 }); scroller.dispatchEvent(new w.Event('scroll'));
assert(!t.root.classList.contains('is-on'), 'scrolling down: hidden');
set({ scrollTop: 1800 }); scroller.dispatchEvent(new w.Event('scroll'));
assert(t.root.classList.contains('is-on'), 'scrolling up after 2+ screens: shown');
assert.equal(d.querySelector('.rt-ring').style.getPropertyValue('--p'), '33');
let scrolled = null; scroller.scrollTo = (o) => { scrolled = o; };
d.querySelector('.rt-pill').click(); assert.equal(scrolled.top, 0);
d.querySelector('.rt-ring').click();
assert(!d.querySelector('.rt-pop').hidden && d.querySelectorAll('.rt-row').length === 4);
assert.equal(d.querySelector('.rt-ring').getAttribute('aria-expanded'), 'true');
d.dispatchEvent(new w.KeyboardEvent('keydown', { key: 'Escape', bubbles: true }));
assert(d.querySelector('.rt-pop').hidden, 'Esc closes');
d.dispatchEvent(new w.KeyboardEvent('keydown', { key: 't', bubbles: true }));
assert(!d.querySelector('.rt-pop').hidden, 'T opens contents');
const rows = d.querySelectorAll('.rt-row'); let seenEl = null; heads[3].el.scrollIntoView = () => { seenEl = heads[3].el; };
rows[3].click(); assert(seenEl && d.querySelector('details').open, 'row opens the details and scrolls');
assert(d.querySelector('.rt-pop').hidden);
// few headings: pill only
content.innerHTML = '<div class="article-detail-card"><h3>T</h3><details><div><h2>One</h2></div></details></div>';
const t2 = rt.mountReadingTools({ scroller, content }); assert(!t2.hasToc && !d.querySelector('.rt-ring') && d.querySelector('.rt-pill'));
assert.equal(d.querySelectorAll('.reading-tools').length, 1, 'one instance');
rt.destroyReadingTools(); assert.equal(d.querySelectorAll('.reading-tools').length, 0);
console.log('TEST 75 OK'); process.exit(0);
