// Fetch state: this-page chip inside the input card + last-summary resume card; resuming restores the stored follow-ups.
import assert from 'assert';
import { setup, imp, tick } from './harness.mjs';
const { w } = setup({}); const d = w.document;
globalThis.requestAnimationFrame = (f) => setTimeout(f, 0);
chrome.runtime.getURL = (p) => 'chrome-extension://abc/' + p;
let tabUrl = 'https://news.example.com/other-story';
chrome.tabs = { query: async () => [{ id: 7, url: tabUrl, title: 'Other story', favIconUrl: '' }], sendMessage: (id, m, cb) => cb && cb({ success: true }), onActivated: { addListener() {} }, onUpdated: { addListener() {} } };
const { default: SM } = await imp('modules/storageManager.js');
const C = await imp('modules/conversation.js');
const { id } = await SM.saveArticle({ content: '<p>c</p>', summary: '<p>sum</p>', url: 'https://a.com/x', title: 'First article' });
await SM.saveConversation(id, [C.newTurn([], { q: 'Why?', a: 'Because.' })]);
const MS = await imp('modules/mainScreen.js');
MS.initMainScreen({ showScreen() {} });
await tick(60);
const card = d.getElementById('pageCard');
assert(card && card.closest('.input-card'), 'page chip sits inside the input card');
assert(card.textContent.includes('Other story') && card.textContent.includes('news.example.com'), 'page metadata');
assert(!card.classList.contains('page-chip--different'), 'neutral when no conversation is active');
assert(!d.getElementById('resumeCard'), 'no resume card any more');
const ask = d.querySelector('#summaryFeed .summary-bubble .ask-btn');
assert(ask, 'Ask on the card replaces it');
ask.click(); await tick(120);
assert.equal(d.querySelector('.controls-bar').dataset.state, 'followup', 'composer morphed to follow-up');
assert(d.querySelector('#summaryFeed .chat-turn-group')?.textContent.includes('Because.'), 'stored turn restored');
assert(!d.getElementById('pageCard') && !d.getElementById('resumeCard'), 'extras gone in follow-up');
assert(d.getElementById('convChip')?.closest('.input-card') && d.getElementById('convChip').textContent.includes('First article') && d.getElementById('convChip').textContent.includes('Continuing'), 'conversation chip in the input card');
assert(!d.getElementById('newSummaryButton'), 'header ＋ New removed');
// ＋ New returns to fetch with the page card and a link back
d.querySelector('#convChip .conv-back').click(); await tick(60);
assert.equal(d.querySelector('.controls-bar').dataset.state, 'fetch');
assert(!d.getElementById('convChip'), 'conversation chip gone after ＋ New');
assert(d.getElementById('pageCard') && !d.getElementById('resumeCard'), 'page card back after ＋ New');
console.log('TEST 46 OK');
