// Read aloud helpers + manifests + sound chip markup.
import { setup, imp } from './harness.mjs'; import assert from 'assert'; import fs from 'fs';
const { w } = setup({}); globalThis.document = w.document; globalThis.window = w;
const r = await imp('modules/reader.js');
const s = r.sentences('Hello world. This is a test! Is it? Yes.');
assert(s.length >= 3 && s.every(x => x.trim()), 'sentences split');
assert.deepEqual(r.finishedSentences('One done. Two done. Thre'), ['One done.', 'Two done.'], 'partial tail is held back');
assert.deepEqual(r.finishedSentences('One done. Thre', true), ['One done.', 'Thre'], 'flush emits the tail');
const t1 = 'The new model, which was trained on a lot of data, is faster. It also costs less';
assert.deepEqual(r.speakable(t1), ['The new model, which was trained on a lot of data,', 'is faster.'].slice(0,0).concat(r.speakable(t1)), 'smoke');
const a = r.speakable('Der neue Ansatz, der auf vielen Daten beruht, ist schneller und');
assert.deepEqual(a, ['Der neue Ansatz, der auf vielen Daten beruht,'], 'clause starts before the sentence ends, tail held');
const b = r.speakable('Der neue Ansatz, der auf vielen Daten beruht, ist schneller und billiger.');
assert.equal(b[0], a[0], 'prefix-stable'); assert.equal(b.length, 2);
assert.deepEqual(r.speakable('Short, bit. Next one here'), ['Short, bit.'], 'tiny clauses are not cut off, tail held');
const qa = w.document.createElement('div');
qa.innerHTML = '<strong class="qa-title">💬 Your questions</strong><div class="chat-turn-group"><div class="chat-q">What is it?</div><div class="chat-a"><div class="chat-a-body">A thing. Really.</div><div class="chat-a-foot"><button class="chat-pin">📌 In article</button></div></div></div>';
assert.deepEqual(r.qaUnits(qa).map(u => u.text), ['Your questions', 'What is it?', 'A thing.', 'Really.'], 'Q&A read, buttons skipped');
const voices = [{ name: 'A', lang: 'en-US' }, { name: 'B', lang: 'de-DE' }];
assert.equal(r.pickVoice(voices, 'de-DE').name, 'B'); assert.equal(r.pickVoice(voices, 'fr-FR'), null);
const root = new URL('../platforms/', import.meta.url).pathname;
assert(JSON.parse(fs.readFileSync(root + 'chrome/manifest.json', 'utf8')).permissions.includes('tts'));
for (const p of ['firefox', 'ios']) assert(JSON.stringify(JSON.parse(fs.readFileSync(root + p + '/manifest.json', 'utf8')).background).includes('ttsEngine.js'), p);
const html = fs.readFileSync(new URL('../src/popup.html', import.meta.url), 'utf8');
assert(!html.includes('compatibleToolsList'));
assert(html.includes('id="chipSound"') && html.includes('id="panelSound"'));
console.log('TEST 77 OK');
