import { setup, imp, tick } from './harness.mjs'; import assert from 'assert';
const day = (n) => { const d = new Date(); d.setDate(d.getDate() - n); d.setHours(0, 0, 0, 0); return d.getTime(); };
const { store, w } = setup({});
const $ = s => w.document.querySelector(s), $$ = s => [...w.document.querySelectorAll(s)];
const click = el => el.dispatchEvent(new w.MouseEvent('click', { bubbles: true }));
const mk = (id, d) => ({ id, feedId: 's1', title: 'T' + id, link: 'https://x/' + id, published: d + 10 * 3600e3, snippet: 's', read: false });
store['feeds:subs'] = [{ id: 's1', url: 'https://a/f', title: 'Alpha', lastFetched: Date.now() }];
store['feeds:items'] = [mk('a', day(0)), mk('b', day(3)), mk('c', day(10))];
store['feeds:ui'] = { source: 'all', status: 'all', date: 'any', mood: 'any', sort: 'new', scope: 'day', anchor: day(3) };
const fm = await imp('modules/feedManager.js'); const ui = { showToast() {}, showScreen() {} };
fm.initFeedManager(ui); await tick(50); await fm.onFeedsScreenShown(ui); await tick(50);
assert.ok($('#feedRecapCard .feed-rc-open'), 'label opens calendar');
assert.ok($('#feedRecapCard .feed-rc-today'), 'today button when not on today');
click($('#feedRecapCard .feed-rc-open')); await tick(20);
const cell = $$('.feed-cal-cell').find(c => c.dataset.day === String(day(10))); assert.ok(cell && !cell.disabled);
click(cell); await tick(30);
assert.equal(store['feeds:ui'].anchor, day(10), 'anchor moved, scope kept'); assert.equal(store['feeds:ui'].scope, 'day'); assert.equal(store['feeds:ui'].date, 'any');
click($('#feedRecapCard .feed-rc-today')); await tick(30);
assert.equal(store['feeds:ui'].anchor, day(0)); assert.ok(!$('#feedRecapCard .feed-rc-today'), 'no today button on today');
// single-day filter view
store['feeds:ui'] = { ...store['feeds:ui'], scope: 'feed', date: { from: day(3), to: day(3) } };
await fm.onFeedsScreenShown(ui); await tick(30);
assert.ok($('.feed-day-header .feed-day-open, .feed-day .feed-day-open'), 'single-day label clickable');
console.log('TEST 22 OK');
