// Article Manager
// Handles article rendering, expand/collapse, search, etc.


import StorageManager from './storageManager.js';

let uiManagerRef = null;

/**
 * Triggers the native OS share sheet
 */
async function shareArticle(article) {
    if (!navigator.share) {
        if (uiManagerRef) uiManagerRef.showToast('Sharing is not supported in this browser/environment.');
        else alert('Sharing is not supported in this browser/environment.');
        return;
    }

    try {
        await navigator.share({
            title: article.title || 'AI Summary',
            text: `Check out this summary: \n\n${article.summary}\n\nRead more at:`,
            url: article.url || ''
        });
    } catch (err) {
        console.error('Share failed:', err);
    }
}

/**
 * Generates and downloads a Markdown file
 */
function exportToMarkdown(article) {
    const timestamp = new Date(article.timestamp).toLocaleDateString();
    const mdContent = `
# ${article.title || 'Untitled Article'}
**Source:** ${article.url || 'Unknown'}
**Date Saved:** ${timestamp}

## 🧙 AI Summary
${article.summary || 'No summary available.'}

---

## 📝 Original Content
${article.content || 'No content available.'}

---
*Generated by AI Summary Helper*
`.trim();

    const blob = new Blob([mdContent], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    
    // Create a filename based on the title
    const safeTitle = (article.title || 'article').replace(/[^a-z0-9]/gi, '_').toLowerCase();
    a.href = url;
    a.download = `${safeTitle}_summary.md`;
    document.body.appendChild(a);
    a.click();
    
    // Cleanup
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
}

export function initArticleManager(uiManager) {
    uiManagerRef = uiManager;
    const historyButton = document.getElementById('historyButton');
    const backButton = document.getElementById('backButton');
    const searchInput = document.getElementById('searchInput');
    const detailBackBtn = document.getElementById('detailBackButton');

    if (detailBackBtn) {
        detailBackBtn.addEventListener('click', () => {
            const articleDetail = document.getElementById('articleDetail');
            const articleList = document.getElementById('articleList');
            const searchInput = document.getElementById('searchInput');
            articleDetail.style.display = 'none';
            if (articleList) articleList.style.display = 'block';
            if (searchInput) searchInput.style.display = 'block';
        });
    }

    if (historyButton) {
        historyButton.addEventListener('click', () => {
            uiManager.showScreen('history');
            loadHistory();
        });
    }
    if (backButton) {
        backButton.addEventListener('click', () => uiManager.showScreen('main'));
    }
    if (searchInput) {
        searchInput.addEventListener('input', filterArticles);
    }

    document.addEventListener('keydown', (event) => {
        if (event.metaKey && event.key === 'f') {
            event.preventDefault();
            const historyNav = document.querySelector('.nav-item[data-screen="history"]');
            if (historyNav && historyNav.classList.contains('active')) {
                searchInput.focus();
            }
        }
    });
}

export function loadHistory() {
    StorageManager.getLocal({ articles: [] }).then(data => {
        renderArticles(data.articles);
    });
}

export function renderArticles(articles) {
    const articleList = document.getElementById('articleList');
    articleList.innerHTML = '';
    if (!articles || articles.length === 0) {
        const emptyMessage = document.createElement('div');
        emptyMessage.id = 'emptyMessage';
        emptyMessage.innerHTML = `<p>🗂️ Your archive is as empty as a desert! Start saving some articles to fill it up. 🌵</p>`;
        articleList.appendChild(emptyMessage);
        return;
    }
    const sortedArticles = articles.sort((a, b) => new Date(b.timestamp) - new Date(a.timestamp));
    sortedArticles.forEach((article) => {
        const articleHeader = article.title || (article.content && article.content.split('\n')[0]) || "No title available";
        const listItem = document.createElement('li');
        listItem.classList.add('article-card');
        const formattedDate = new Date(article.timestamp).toLocaleDateString(undefined, { year: 'numeric', month: 'short', day: 'numeric' });
        const formattedTime = new Date(article.timestamp).toLocaleTimeString(undefined, { hour: '2-digit', minute: '2-digit' });
        let articleDomain = '';
        if (article.url) {
            articleDomain = new URL(article.url).hostname;
        }
        const safeSummary = (article.summary || 'No summary available').replace(/<img[^>]*>/gi, '');
        listItem.innerHTML = `
            <div class="article-header">
              <div>
                <h4>${articleHeader}</h4>
                <p class="article-date">💾 ${formattedDate} ${article.url ? `from <a href="${article.url}" target="_blank">${articleDomain}</a> ↗` : ''}
              </div>
              <button class="button-secondary open-article-button">Open</button>
            </div>
        `;
        articleList.appendChild(listItem);

        const openButton = listItem.querySelector('.open-article-button');
        const shareButton = listItem.querySelector('.share-button');
        const mdButton = listItem.querySelector('.md-button');
        const deleteButton = listItem.querySelector('.delete-button');

        if (openButton) {
            openButton.addEventListener('click', (e) => {
                e.stopPropagation();
                showArticleDetail(article);
            });
        }
        // Click on the card itself also opens detail
        listItem.addEventListener('click', (event) => {
            if (event.target.closest('button') || event.target.closest('a')) return;
            showArticleDetail(article);
        });
    });
}

export function filterArticles() {
    const searchInput = document.getElementById('searchInput');
    const filterText = searchInput.value.toLowerCase();
    const articles = document.querySelectorAll('.article-card');
    articles.forEach(article => {
        const headerText = article.querySelector('.article-header h4').textContent.toLowerCase();
        const matches = headerText.includes(filterText);
        article.style.display = matches ? 'block' : 'none';
    });
}

export function displayArticleDetails(data) {
    // No longer used — detail view is now handled by showArticleDetail()
}

/**
 * Shows the full article detail view with back button
 */
export function showArticleDetail(article) {
    const articleList = document.getElementById('articleList');
    const searchInput = document.getElementById('searchInput');
    const articleDetail = document.getElementById('articleDetail');
    const articleDetailContent = document.getElementById('articleDetailContent');
    const backBtn = document.getElementById('detailBackButton');

    if (!articleDetail || !articleDetailContent) return;

    const safeTitle = article.title || (article.content && article.content.split('\n')[0]) || 'Article';
    const safeSummary = (article.summary || 'No summary available').replace(/<img[^>]*>/gi, '');
    const safeContent = (article.content || 'No content available').replace(/<img[^>]*>/gi, '');
    const domain = article.url ? (() => { try { return new URL(article.url).hostname; } catch { return ''; } })() : '';

    articleDetailContent.innerHTML = `
      <div class="article-detail-card">
        <h3 style="margin-bottom:8px;">${safeTitle}</h3>
        <p style="font-size:12px;color:var(--text-muted);margin-bottom:16px;">
          ${article.url ? `<a href="${article.url}" target="_blank">${domain} ↗</a> · ` : ''}
          ${new Date(article.timestamp).toLocaleDateString()}
        </p>
        <div class="action-bar" style="margin-bottom:16px;display:flex;gap:8px;flex-wrap:wrap;">
          <button class="button-secondary share-button">Share 🔗</button>
          <button class="button-secondary md-button">.MD 💾</button>
          <button class="button-secondary open-button">Reader 👓</button>
          <button class="delete-button" style="margin-left:auto;">🗑️ Delete</button>
        </div>
        <div class="summary-box" style="background:rgba(0,0,0,0.05);padding:12px;border-radius:8px;border-left:4px solid #007bff;margin-bottom:16px;">
          <strong style="display:block;margin-bottom:8px;">🧙 AI Summary</strong>
          <div>${safeSummary}</div>
        </div>
        <details style="margin-top:8px;">
          <summary style="cursor:pointer;font-weight:600;color:var(--text-secondary);">📄 Original Content</summary>
          <p style="font-size:13px;opacity:0.85;margin-top:8px;">${safeContent}</p>
        </details>
      </div>
    `;

    // Wire up buttons
    const shareBtn = articleDetailContent.querySelector('.share-button');
    const mdBtn = articleDetailContent.querySelector('.md-button');
    const openBtn = articleDetailContent.querySelector('.open-button');
    const deleteBtn = articleDetailContent.querySelector('.delete-button');

    if (shareBtn) shareBtn.addEventListener('click', (e) => { e.stopPropagation(); shareArticle(article); });
    if (mdBtn) mdBtn.addEventListener('click', (e) => { e.stopPropagation(); exportToMarkdown(article); });
    if (openBtn) {
        openBtn.addEventListener('click', (e) => {
            e.stopPropagation();
            const newTab = window.open();
            newTab.document.write(`
                <html><head><title>${safeTitle}</title>
                <style>body{font-family:Georgia,serif;padding:20px;max-width:800px;margin:auto;background:#f4f4f4;color:#333;line-height:1.6;}
                h2{color:#444;}pre{white-space:pre-wrap;word-wrap:break-word;}</style></head>
                <body><h2>Summary</h2><p>${article.summary}</p><h2>Content</h2><pre>${article.content}</pre></body></html>
            `);
            newTab.document.close();
        });
    }
    if (deleteBtn) {
        deleteBtn.addEventListener('click', function (e) {
            e.stopPropagation();
            if (confirm('Are you sure you want to delete this article?')) {
                StorageManager.getLocal('articles').then(data => {
                    const articles = data.articles || [];
                    const updated = articles.filter(item => item.timestamp !== article.timestamp);
                    StorageManager.setLocal({ articles: updated }, () => {
                        renderArticles(updated);
                        articleDetail.style.display = 'none';
                        if (articleList) articleList.style.display = 'block';
                        if (searchInput) searchInput.style.display = 'block';
                    });
                });
            }
        });
    }

    // Show detail, hide list
    if (articleList) articleList.style.display = 'none';
    if (searchInput) searchInput.style.display = 'none';
    articleDetail.style.display = 'block';
}
