// Article Manager
// Handles article rendering, expand/collapse, search, etc.


import StorageManager from './storageManager.js';

let uiManagerRef = null;

/**
 * Triggers the native OS share sheet
 */
async function shareArticle(article) {
    if (!navigator.share) {
        if (uiManagerRef) uiManagerRef.showToast('Sharing is not supported in this browser/environment.');
        else alert('Sharing is not supported in this browser/environment.');
        return;
    }

    try {
        await navigator.share({
            title: article.title || 'AI Summary',
            text: `Check out this summary: \n\n${article.summary}\n\nRead more at:`,
            url: article.url || ''
        });
    } catch (err) {
        console.error('Share failed:', err);
    }
}

/**
 * Generates and downloads a Markdown file
 */
function exportToMarkdown(article) {
    const timestamp = new Date(article.timestamp).toLocaleDateString();
    const mdContent = `
# ${article.title || 'Untitled Article'}
**Source:** ${article.url || 'Unknown'}
**Date Saved:** ${timestamp}

## 🧙 AI Summary
${article.summary || 'No summary available.'}

---

## 📝 Original Content
${article.content || 'No content available.'}

---
*Generated by AI Summary Helper*
`.trim();

    const blob = new Blob([mdContent], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    
    // Create a filename based on the title
    const safeTitle = (article.title || 'article').replace(/[^a-z0-9]/gi, '_').toLowerCase();
    a.href = url;
    a.download = `${safeTitle}_summary.md`;
    document.body.appendChild(a);
    a.click();
    
    // Cleanup
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
}

export function initArticleManager(uiManager) {
    uiManagerRef = uiManager;
    const historyButton = document.getElementById('historyButton');
    const backButton = document.getElementById('backButton');
    const historyScreen = document.getElementById('historyScreen');
    const searchInput = document.getElementById('searchInput');

    if (historyButton) {
        historyButton.addEventListener('click', () => {
            uiManager.showScreen('history');
            loadHistory();
        });
    }
    if (backButton) {
        backButton.addEventListener('click', () => uiManager.showScreen('main'));
    }
    if (searchInput) {
        searchInput.addEventListener('input', filterArticles);
    }

    document.addEventListener('keydown', (event) => {
        if (event.metaKey && event.key === 'f') {
            event.preventDefault();
            if (historyScreen.style.display === 'block') {
                searchInput.focus();
            }
        }
    });
}

export function loadHistory() {
    StorageManager.getLocal({ articles: [] }).then(data => {
        renderArticles(data.articles);
    });
}

export function renderArticles(articles) {
    const articleList = document.getElementById('articleList');
    articleList.innerHTML = '';
    if (!articles || articles.length === 0) {
        const emptyMessage = document.createElement('div');
        emptyMessage.id = 'emptyMessage';
        emptyMessage.innerHTML = `<p>🗂️ Your archive is as empty as a desert! Start saving some articles to fill it up. 🌵</p>`;
        articleList.appendChild(emptyMessage);
        return;
    }
    const sortedArticles = articles.sort((a, b) => new Date(b.timestamp) - new Date(a.timestamp));
    sortedArticles.forEach((article) => {
        const articleHeader = article.title || article.content.split('\n')[0] || "No title available";
        const listItem = document.createElement('li');
        listItem.classList.add('article-card');
        const formattedDate = new Date(article.timestamp).toLocaleDateString(undefined, { year: 'numeric', month: 'short', day: 'numeric' });
        const formattedTime = new Date(article.timestamp).toLocaleTimeString(undefined, { hour: '2-digit', minute: '2-digit' });
        let articleDomain = '';
        if (article.url) {
            articleDomain = new URL(article.url).hostname;
        }
        listItem.innerHTML = `
            <div class="article-header">
              <div>
                <h4>${articleHeader}</h4>
                <p class="article-date">💾 ${formattedDate} ${article.url ? `from <a href="${article.url}" target="_blank">${articleDomain}</a> ↗` : ''}
              </div>
              <button class="button-secondary expand-button">Expand</button>
            </div>
            <div class="article-content" style="display: none;">
              <div class="action-bar" style="margin-bottom: 12px; display: flex; gap: 8px;">
                <button class="button-secondary share-button">Share 🔗</button>
                <button class="button-secondary md-button">Export .MD 📝</button>
                <button class="button-secondary open-button">Read Full 👓</button>
                <button class="delete-button" aria-label="Delete article" style="margin-left: auto;">🗑️</button>
              </div>
              <p><strong>Description:</strong> ${article.description || 'No description available'}</p>
              <div class="summary-box" style="background: rgba(0,0,0,0.05); padding: 10px; border-radius: 8px; border-left: 4px solid #007bff; margin-bottom: 12px;">
                <strong>Summary:</strong><br>${article.summary || 'No summary available'}
              </div>
              <p style="font-size: 0.9em; opacity: 0.8; margin-top: 10px;"><strong>Original Content:</strong><br>${article.content || 'No content available'}</p>
            </div>
        `;
        articleList.appendChild(listItem);

        const expandButton = listItem.querySelector('.expand-button');
        const articleContent = listItem.querySelector('.article-content');
        const openButton = listItem.querySelector('.open-button');
        const shareButton = listItem.querySelector('.share-button');
        const mdButton = listItem.querySelector('.md-button');
        const deleteButton = listItem.querySelector('.delete-button');

        if (expandButton && articleContent) {
            expandButton.addEventListener('click', (e) => {
                e.stopPropagation();
                const isVisible = articleContent.style.display === 'block';
                articleContent.style.display = isVisible ? 'none' : 'block';
                expandButton.textContent = isVisible ? 'Expand' : 'Collapse';
            });
        }
        if (openButton) {
            openButton.addEventListener('click', (e) => {
                e.stopPropagation();
                const newTab = window.open();
                newTab.document.write(`
                    <html>
                      <head>
                        <title>Article Details</title>
                        <style>
                          body { font-family: 'Georgia', serif; padding: 20px; max-width: 800px; margin: auto; background-color: #f4f4f4; color: #333; line-height: 1.6; }
                          h2 { color: #444; }
                          p, pre { line-height: 1.6; }
                          pre { white-space: pre-wrap; word-wrap: break-word; }
                        </style>
                      </head>
                      <body>
                        <h2>Summary</h2>
                        <p>${article.summary}</p>
                        <h2>Content</h2>
                        <pre>${article.content}</pre>
                      </body>
                    </html>
                `);
                newTab.document.close();
            });
        }
        if (shareButton) {
            shareButton.addEventListener('click', (e) => {
                e.stopPropagation();
                shareArticle(article);
            });
        }
        if (mdButton) {
            mdButton.addEventListener('click', (e) => {
                e.stopPropagation();
                exportToMarkdown(article);
            });
        }
        if (deleteButton) {
            deleteButton.addEventListener('click', function (e) {
                e.stopPropagation();
                if (confirm('Are you sure you want to delete this article?')) {
                    StorageManager.getLocal('articles').then(data => {
                        const articles = data.articles || [];
                        const updatedArticles = articles.filter((item) => item.timestamp !== article.timestamp);
                        StorageManager.setLocal({ articles: updatedArticles }, () => {
                            renderArticles(updatedArticles);
                        });
                    });
                }
            });
        }
        /*
        listItem.addEventListener('click', (event) => {
            if (!event.target.classList.contains('expand-button')) {
                const isVisible = articleContent.style.display === 'block';
                articleContent.style.display = isVisible ? 'none' : 'block';
                expandButton.textContent = isVisible ? 'Expand' : 'Collapse';
            }
        });
        */
    });
}

export function filterArticles() {
    const searchInput = document.getElementById('searchInput');
    const filterText = searchInput.value.toLowerCase();
    const articles = document.querySelectorAll('.article-card');
    articles.forEach(article => {
        const headerText = article.querySelector('.article-header h4').textContent.toLowerCase();
        const contentText = article.querySelector('.article-content').textContent.toLowerCase();
        if (headerText.includes(filterText) || contentText.includes(filterText)) {
            article.style.display = 'block';
        } else {
            article.style.display = 'none';
        }
    });
}

export function displayArticleDetails(data) {
    const articleDetailsContainer = document.getElementById('articleDetails');
    articleDetailsContainer.innerHTML = `
      <h3>Article Details</h3>
      <p><strong>Title:</strong> ${data.title || 'No title available'}</p>
      <p><strong>Description:</strong> ${data.description || 'No description available'}</p>
      <p><strong>URL:</strong> <a href="${data.url}" target="_blank">${data.url}</a></p>
    `;
}
